Game.Level01 = {
	load: function(map) {
		map.defineObject("block", Game.Map.Wall);
		map.defineObject("blinky", new Game.Map.Ghost(1));
		map.defineObject("pinky", new Game.Map.Ghost(2));
		map.defineObject("inky", new Game.Map.Ghost(3));
		map.defineObject("clyde", new Game.Map.Ghost(4));
		map.defineObject("food", Game.Map.Food );

		Game.Level01.buildMaze(map, this.Walls);

	},

	buildMaze: function(map, Walls) {
		for (var y = 0; y < Walls.length; y++) {
			for (var x = 0; x < Walls[y].length; x++) {
				switch( Walls[y][x] ) {
					case 'W': map.placeObject(x, y, 'block');
						break;
					case '*': map.placeObject(x, y, 'food');
						break;
					case 'P': map.addDynamic(x, y, "pinky");
						break;
					case 'B': map.addDynamic(x, y, "blinky");
						break;
					case 'I' : map.addDynamic(x, y, "inky");
						break;
					case 'C' : map.addDynamic(x, y, "clyde");
						break;
					case 'O' : map.placePlayer(x, y, 0);
						break;
				}
			};
		};
	},

	Walls: [
		'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
		'WWW__________________________________________________________________________WWW',
		'WWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW__O_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWW',
		'W______________________________________________________________________________W',
		'W_W_WWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWW_WW_WWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWW_W_W',
		'W_W_WW_______________________*_______W_WW_W______*________________________WW_W_W',
		'W_W_WW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW_W_WW_W_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WW_W_W',
		'W_W_WW_WW_________________________WW_W_WW_W_WW_________________________WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W_WW_W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W_WW_W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W_WW_W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W_WW_W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W_WW_W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W____W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WWWWWW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW________WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WWWW_WW_WWWW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WWWW_WW_WWWW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW______________________________________________________________WW_WW_W_W',
		'W_W_WW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_PI_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WW_W_W',
		'W_W_WW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_CB_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WW_W_W',
		'W_W_WW_WW______________________________________________________________WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WWWW_WW_WWWW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WWWW_WW_WWWW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW________WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WWWWWW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W____W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W_WW_W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W_WW_W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W_WW_W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W_WW_W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_W_WW_W_WW_WWWWWWWWWWWWWWWWWWWWWWW_WW_WW_W_W',
		'W_W_WW_WW_________________________WW_W_WW_W_WW_________________________WW_WW_W_W',
		'W_W_WW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW_W_WW_W_WWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WW_W_W',
		'W_W_WW_______________________________W_WW_W_______________________________WW_W_W',
		'W_W_WWWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWW_WW_WWWWWWWWWWWWWWWW_WWWWWWWWWWWWWWWWW_W_W',
		'W______________________________________WW______________________________________W',
		'WWW_WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW____WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_WWW',
		'WWW____________________________________WW____________________________________WWW',
		'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'
	]
}